### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by joey-kilgore** [Beachwood-High-School/Hyland2020#4]
I'm not entirely sure what this project was or what it is about. Updating the README.md file in the main directory would allow anyone looking at this repository to see its uses. I would also recommend giving instructions for installation, and maybe even screenshots of the software.  
For github markdown tips see [THIS LINK](https://guides.github.com/features/mastering-markdown/)

**Comment by karmanyaahm** [comment]
A little late 😛, but fixed now from baaa7ccb to 95cd7bd5.
